import Head from "next/head";
import SVGNodeEditor from "@/components/SVGNodeEditor";
import Layout from "@/components/TEMP_blockout/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ransuu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
      {/* <main className="flex gap-1 items-center p-24 h-screen w-screen">
        <SVGNodeEditor />
      </main> */}
    </>
  );
}
