import Head from "next/head";
import dynamic from "next/dynamic";
import styles from "@/styles/Home.module.css";
import BasicFlow from "@/components/BasicFlow";

const SVGOutput = dynamic(() => import("@/components/SVGOutput"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Ransuu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <BasicFlow />
        <SVGOutput />
      </main>
    </>
  );
}
