import Head from "next/head";
import styles from "@/styles/Home.module.css";
import BasicFlow from "@/components/BasicFlow";
import SVGOutput from "@/components/SVGOutput";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ransuu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <BasicFlow />
        <SVGOutput width={512} height={512}>
          <path fill="#063855" fillRule="evenodd" d="M0 0h48v1H0z" />
        </SVGOutput>
      </main>
    </>
  );
}
